@Api.EF_HostAddress = https://localhost:7101

GET {{Api.EF_HostAddress}}/health
Accept: application/json

###

GET {{Api.EF_HostAddress}}/books/
Accept: application/json

###

GET {{Api.EF_HostAddress}}/books/1
Accept: application/json

###

POST {{Api.EF_HostAddress}}/books/
Content-Type: application/json
Accept: application/json

{
  "id": 6,
  "title": "The Lord of the Rings",
  "authorId": 6,
  "authorName": "C. Hurst",
  "yearPublished": 1954,
  "genre": "Fantasy"
}

###

PUT {{Api.EF_HostAddress}}/books/
Content-Type: application/json
Accept: application/json

{
  "id": 6,
  "title": "The Lord of the Rings",
  "authorName": "J.R.R. Tolkien",
  "authorId": 3,
  "yearPublished": 1954,
  "genre": "Fantasy"
}

###

DELETE {{Api.EF_HostAddress}}/books/6
Accept: application/json

###


GET {{Api.EF_HostAddress}}/books/6
Accept: application/json

###

GET {{Api.EF_HostAddress}}/crash
Accept: application/json

###

GET {{Api.EF_HostAddress}}/authors/
Accept: application/json

###

GET {{Api.EF_HostAddress}}/authors/1
Accept: application/json

###

GET {{Api.EF_HostAddress}}/authors/3/books
Accept: application/json

###

POST {{Api.EF_HostAddress}}/authors/
Content-Type: application/json
Accept: application/json

{
  "id": 6,
  "name": "CHurst"
}

###

PUT {{Api.EF_HostAddress}}/authors/
Content-Type: application/json
Accept: application/json

{
  "id": 6,
  "name": "C. Hurst"
}

###

DELETE {{Api.EF_HostAddress}}/authors/6
Content-Type: application/json
Accept: application/json